
services:
  ml-service:
    build: .
    image: sss:latest
    ports:
      - "5000:5000"    
    depends_on:
      - jaeger
    networks:
      - mynetwork

  jaeger:
    image: jaegertracing/all-in-one:1.47
    container_name: jaeger
    ports:
      - "6831:6831/udp"   # Jaeger agent port (UDP)
      - "16686:16686"     # Jaeger UI
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge